### ISSUE TITLE
function flatten_chr not found

### ISSUE THREAD

**Issue by t-0-m-1-3** [MangoTheCat/blog_GoTr#1]
![image](https://user-images.githubusercontent.com/20537914/30654583-4e9ac29e-9dfc-11e7-9ad8-2b2aa920da16.png)

Hi,
I'm running through your tutorial on the API and am running into some issues trying to use:
# Retrieve pov characters data in book 5
povData <- books_5$povCharacters %>% 
  flatten_chr() %>%
  map(function(x) got_api(url = x))

I was missing magrittr and that took care of an issue i had with %>% not being found, is there another dependency I'm missing?

**Comment by dougmet** [comment]
I believe flatten_chr is from the purrr package. So try

```
library(purrr)
```

Alternatively load everything you could need in one go with

```
library(tidyverse)
```

**Comment by Avatoo** [comment]
Three packages are required and thus loaded at the top of the blogpost script. **flatten_chr** and **map** are both from `tidyverse` or more specifically `purrr` as @dougmet suggested. Can you please try again?
```
library(GoTr)
library(tidyverse)
library(listviewer)
```

**Comment by t-0-m-1-3** [comment]
many thanks @dougmet and @Avatoo 

library(purrr) was the reason.
